export const constant ={
    secret: 'eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTYzNzAzMjEyOSwiaWF0IjoxNjM3MDMyMTI5fQ.wl2_-nPXWCiCxg8byCrED8X10jqpWBg5tNXz8JkCQSY'
};